language: rust
sudo: false

cache: cargo

matrix:
  include:
    # Builds with wasm-pack.
    - rust: beta
      env: RUST_BACKTRACE=1
      addons:
        firefox: latest
        chrome: stable
      before_script:
        - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
        - (test -x $HOME/.cargo/bin/cargo-generate || cargo install cargo-generate)
        - cargo install-update -a
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
      script:
        - cargo generate --git . --name testing
        # Having a broken Cargo.toml (in that it has curlies in fields) anywhere
        # in any of our parent dirs is problematic.
        - mv Cargo.toml Cargo.toml.tmpl
        - cd testing
        - wasm-pack build
        - travis_wait 30 wasm-pack test --chrome --firefox --headless
