[package]
name = "libenchcrack"
description = "Code for cracking minecraft's XP seed"
version = "0.1.0"
authors = ["ImUrX <urielfontan2002@gmail.com>"]
edition = "2018"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.63"
console_error_panic_hook = { version = "0.1.6", optional = true }
wee_alloc = "0.4.5"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[dependencies.web-sys]
version = "0.3.44"
features = [
    "console"
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true
